$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command
name: train_model
version: 1

display_name: Train Logistic Regression
code: ../scripts
command: >-
  python train_lr.py --config_path ${{inputs.config_path}}

inputs:
  config_path:
    type: uri_file

environment:
  conda_file: ../env/conda.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

description: "Reusable component for training LR"