# platform specific config.yaml
platform:
  provider: "azure"
  compute: "azureml:prototypecomputea1"
#  role: "arn:aws:iam::123456789:role/SageMakerExecutionRole"  # only for AWS
#  region: "eastus"  # Azure region (if applicable)
#  s3_bucket: "my-ml-bucket"  # AWS S3 bucket name (if applicable)
job:
  base_job_name: "training-pipeline"
  config_path: ./config/config.yaml
  scripts:
    - train_lr.py
    - train_rf.py
    - validate_model.py