name: AzureML Model Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-pipeline:
    name: Submit AML Jobs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure ML CLI extension
      run: |
        az extension add -n ml -y
        az configure --defaults group=${{ secrets.AZURE_RESOURCE_GROUP }} workspace=${{ secrets.AZURE_ML_WORKSPACE }}

    - name: Submit Train Job
      run: az ml job create --file jobs/train_job.yaml

    - name: Submit Validate Job
      run: az ml job create --file jobs/validate_job.yaml

    - name: Submit Register Job
      run: az ml job create --file jobs/register_job.yaml

    - name: Optionally Submit Full Pipeline
      run: az ml job create --file jobs/pipeline_job.yaml
