mlflow:
  tracking_uri: "http://localhost:5000"
platform:
  use_azureml: True
data:
  path: "./data/train_data.csv"
  target_column: "target"
  output_dir: "./Outputs"
models:
  - name: model_lr
    experiment_name: "Logistic_Regression_Training"
    run_name: "lr_training"
    model_name: "LogisticRegressionModel"
    model_version: "1.0.0"
    model_description: "Logistic Regression model for binary classification"
    model_tags:
      framework: "scikit-learn"
      version: "1.0.2"
      license: "MIT"
    hyperparameters:
      C: 1.0
      solver: "lbfgs"
      max_iter: 100       
    model_input_schema:         
      type: "object"
      properties:
        feature1:
          type: "number"
          description: "Feature 1 description"
        feature2:
          type: "number"
          description: "Feature 2 description"
      required:
        - feature0
        - feature1
        - feature2
        - feature3
        - feature4
        - feature5
        - feature6
        - feature7
        - feature8 
        - feature9
    model_output_schema:
      type: "object"
      properties:
        prediction:
          type: "number"
          description: "Predicted value"
      required:
        - prediction  
  - name: model_rf
    experiment_name: "Random_Forest_Training"
    run_name: "rf_training"
    model_name: "RandomForestModel"
    model_version: "1.0.0"
    model_description: "Random Forest model for binary classification"
    model_tags:
      framework: "scikit-learn"
      version: "1.3.2"
      license: "MIT"
    hyperparameters:
      n_estimators: 150
      max_depth: 10
      random_state: 42
      model_input_schema:
        type: "object"
        properties:
          feature1:
            type: "number"
            description: "Feature 1"
          feature2:
            type: "number"
            description: "Feature 2"
        required:
          - feature0
          - feature1
          - feature2
          - feature3
          - feature4
          - feature5
          - feature6
          - feature7
          - feature8
          - feature9
      model_output_schema:
        type: "object"
        properties:
          prediction:
            type: "number"
            description: "Predicted value"
        required:
          - prediction
metrics_threshold:
  accuracy: 0.76
  precision: 0.73
  recall: 0.71
  f1_score: 0.72
                 